### ISSUE TITLE
Cannot download the plugin

### ISSUE THREAD

**Issue by itsboredd** [marzent/IINACT#103]
![image_2024-07-31_184429190](https://github.com/user-attachments/assets/3db86f0e-acad-481c-ab45-8697e0afa98a)

**Comment by shadowking1443** [comment]
I can second this issue. Even after deleting and reinstalling the plugin, the issue persists.

**Comment by marzent** [comment]
Would you be able to share the Malamud log of when this happens via `/xllog`?

**Comment by darkcloud89** [comment]
Not sure if this is the exact same issue as OP, but this is what is in the log when I get this error:

```
2024-08-05 00:40:06.584 -04:00 [ERR] [LOCALPLUGIN] Exception during plugin initialization
System.AggregateException: Failed to create IINACT.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'GetThreadDpiHostingBehavior' in DLL 'USER32.dll'.
   at System.Windows.Forms.DpiHelper.DpiAwarenessScope..ctor(DPI_AWARENESS_CONTEXT context, DPI_HOSTING_BEHAVIOR behavior)
   at System.Windows.Forms.DpiHelper.EnterDpiAwarenessScope(DPI_AWARENESS_CONTEXT awareness, DPI_HOSTING_BEHAVIOR dpiHosting)
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Application.ThreadContext.get_MarshalingControl()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..ctor()
   at System.Windows.Forms.WindowsFormsSynchronizationContext.InstallIfNeeded()
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
   at System.Windows.Forms.ScrollableControl..ctor()
   at System.Windows.Forms.ContainerControl..ctor()
   at System.Windows.Forms.Form..ctor()
   at Advanced_Combat_Tracker.FormActMain..ctor(IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/NotACT/FormActMain.cs:line 31
   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 75
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
--- End of stack trace from previous location ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
   --- End of inner exception stack trace ---
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
   at Dalamud.Plugin.Internal.Types.LocalPlugin.<LoadAsync>g__Create|69_1() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 422
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 419
 ```

Doesn't seem to be effected one way or the other by the "DPI Aware" setting in XIVLauncher.

**Comment by marzent** [comment]
@darkcloud89 Are you on Windows 7?

**Comment by darkcloud89** [comment]
Sorry, meant to add that this was running on Linux (via XIVLauncher.Core)

**Comment by marzent** [comment]
@darkcloud89 your issue is a duplicate of https://github.com/marzent/IINACT/issues/78

**Comment by marzent** [comment]
Not sure about the original load error here… Hard to say without more info/logs.

**Comment by Scalecat** [comment]
Same issue.  Windows 11.

`12:53:24.100 | ERR | [LOCALPLUGIN] Exception during plugin initialization
	System.AggregateException: Failed to create IINACT.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Burd\Documents\IINACT' is denied.
	   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
	   at System.IO.Directory.CreateDirectory(String path)
	   at FFXIV_ACT_Plugin.Logfile.LogOutput.ConfigureLogFile()
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   at IINACT.FfxivActPluginWrapper.SetupSettingsMediator() in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 250
	   at IINACT.FfxivActPluginWrapper..ctor(Configuration configuration, ClientLanguage dalamudClientLanguage, IChatGui chatGui) in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 142
	   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 83
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<LoadAsync>g__Create|69_1() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 422
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 419
12:53:24.113 | ERR | [LOCALPLUGIN] Error while loading "IINACT", failed to bind and call the plugin constructor
`

**Comment by shadowking1443** [comment]
> Not sure about the original load error here… Hard to say without more info/logs.

Hi Marzent,

Sorry for the delay log is below.

```
19:35:36.943 | INF | [PROFILE] Removing plugin "IINACT"(1b85a2ab-25a6-4c22-a912-db5d2bee42f2) from profile 00000000-0000-0000-0000-000000000000
19:35:36.971 | INF | [PLUGINM] Installed plugin IINACT (testing=False)
19:35:36.971 | INF | [PLUGINM] Loading plugin IINACT
19:35:36.972 | WRN | [PROFMAN] '73861471-a117-4514-b2e0-8522013c43a3'('"IINACT"') was not in any profile, adding to default with True
19:35:36.973 | INF | [PROFILE] Adding plugin "IINACT"(73861471-a117-4514-b2e0-8522013c43a3) to profile 00000000-0000-0000-0000-000000000000 with state True
19:35:36.973 | INF | [PLUGINM] "IINACT" defaultState: True wantedByAnyProfile: True loadPlugin: True
19:35:36.973 | INF | [LOCALPLUGIN] Loading IINACT.dll
19:35:39.621 | INF | [IINACT] [MACHINA] Using FFXIV Opcodes for game region Global
19:35:41.386 | ERR | [LOCALPLUGIN] Error while loading "IINACT", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create IINACT.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Ryan Thompson\Documents\IINACT' is denied.
	   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
	   at System.IO.Directory.CreateDirectory(String path)
	   at FFXIV_ACT_Plugin.Logfile.LogOutput.ConfigureLogFile()
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
	   at IINACT.FfxivActPluginWrapper.SetupSettingsMediator() in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 208
	   at IINACT.FfxivActPluginWrapper..ctor(Configuration configuration, ClientLanguage dalamudClientLanguage, IChatGui chatGui, IFramework framework, ICondition condition) in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 111
	   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IFramework framework, ICondition condition, IPluginLog pluginLog, IGameInteropProvider gameInteropProvider, ISigScanner sigScanner) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 98
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 583
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 581
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 396
```
