### ISSUE TITLE
Plugin loading/installation error

### ISSUE THREAD

**Issue by plivdev** [marzent/IINACT#106]
Hi, I have a big problem since yesturday, IINACT refuse to load, logs:
```22:53:38.049 | INF | [PLUGINR] Fetching repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json
22:53:38.303 | INF | [PLUGINR] Successfully fetched repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json
22:54:18.254 | INF | [PLUGINR] Fetching repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json
22:54:18.273 | INF | [PLUGINR] Successfully fetched repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json
22:54:39.732 | INF | [PROFILE] Removing plugin "IINACT"(cef24940-8433-47ee-b0f8-0c51cb09b91c) from profile 00000000-0000-0000-0000-000000000000
22:54:39.777 | INF | [PLUGINM] Installed plugin IINACT (testing=False)
22:54:39.777 | INF | [PLUGINM] Loading plugin IINACT
22:54:39.777 | WRN | [PROFMAN] '8de3009e-818f-4fbb-8b44-e8793abfe565'('"IINACT"') was not in any profile, adding to default with True
22:54:39.778 | INF | [PROFILE] Adding plugin "IINACT"(8de3009e-818f-4fbb-8b44-e8793abfe565) to profile 00000000-0000-0000-0000-
[22:58]
000000000000 with state True
22:54:39.778 | INF | [PLUGINM] "IINACT" defaultState: True wantedByAnyProfile: True loadPlugin: True
22:54:39.778 | INF | [LOCALPLUGIN] Loading IINACT.dll
22:54:42.841 | INF | [IINACT] [MACHINA] Using FFXIV Opcodes for game region Global
22:54:44.523 | INF | [IINACT] [FFXIV_ACT_PLUGIN] ReadProcesses.GetProcesses() error: System.ComponentModel.Win32Exception (5): Accès refusé.   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)   at System.Diagnostics.Process.GetProcessTimes()   at System.Diagnostics.Process.get_StartTime()   at FFXIV_ACT_Plugin.Memory.MemoryReader.ReadProcesses.Read64(Boolean verifyMainModule)
    System.AggregateException: Failed to create IINACT.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
       at IINACT.FfxivActPluginWrapper.SetupSettingsMediator() in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 254
       at IINACT.FfxivActPluginWrapper..ctor(Configuration configuration, ClientLanguage dalamudClientLanguage, IChatGui chatGui) in /home/runner/work/IINACT/IINACT/IINACT/FfxivActPluginWrapper.cs:line 142
       at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 83
22:54:44.543 | ERR | [LOCALPLUGIN] Error while loading "IINACT", failed to bind and call the plugin constructor
22:55:08.774 | INF | [PLUGINR] Fetching repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json
22:55:08.792 | INF | [PLUGINR] Successfully fetched repo: https://raw.githubusercontent.com/marzent/IINACT/main/repo.json```

**Comment by marzent** [comment]
You will have to unfortunately restart your PC, this is an issue with FFXIV_ACT_PLUGIN when you have a dead FFXIV process still flying around, there is not too much I can do there...

**Comment by Riiskyy** [comment]
im also getting this issue. I've rebooted my PC multiple times, tried deleting the iinact folder from dalamud installedPlugins folder and restarted the game multiple times

```23:44:56.278 | ERR | [LOCALPLUGIN] Exception during plugin initialization
	System.AggregateException: Failed to create IINACT.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.AggregateException: One or more errors occurred. (A task was canceled.)
	 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
	   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at FetchDependencies.FetchDependencies.DownloadFile(String url, String path) in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 83
	   at FetchDependencies.FetchDependencies.GetFfxivPlugin() in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 38
	   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 70
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
	   at FetchDependencies.FetchDependencies.DownloadFile(String url, String path) in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 83
	   at FetchDependencies.FetchDependencies.GetFfxivPlugin() in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 38
	   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 70
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<LoadAsync>g__Create|69_1() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 422
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 419
23:44:56.295 | ERR | [LOCALPLUGIN] Error while loading "IINACT", failed to bind and call the plugin constructor
```

**Comment by marzent** [comment]
@Riiskyy you are having a network issue where it cannot download the original FFXIV_ACT_Plugin

**Comment by Riiskyy** [comment]
If I download it manually where would I need to place it?

**Comment by Riiskyy** [comment]
nvm dropiing it in the iinact folder seemed to work

**Comment by marzent** [comment]
Since both of these exceptions are out of my control (and have an easy fix), I'll be closing this for now.

**Comment by Riiskyy** [comment]
is there any way i can test why the plugin is failing to download? Where is it downloading from? I don'twant to have to recopy the plugin manually eevery time there is an iinact update and have to restart my game again

**Comment by Kataiser9** [comment]
> nvm dropiing it in the iinact folder seemed to work

Hey - sorry to resurrect this, but I've suddenly started having the problem you mentioned as well (same error in the log). Changing DNS providers (as you mentioned in #110) didn't help. So I tried manually downloading the original FFXIV_ACT_Plugin and putting it in the IINACT folder as you mentioned - also didn't help. So just to double-check, what's the exact filepath the .dll should be in? Currently I have it as ~/installedPlugins/IINACT/2.8.3.2/FFXIV_ACT_Plugin.dll but I'm still getting the same error.

Is there somewhere else it's supposed to go? This is getting frustrating.
