### ISSUE TITLE
Overlays do not appear to recieve any combat data.

### ISSUE THREAD

**Issue by SMNIRL** [marzent/IINACT#11]
None of the overlays react to damage or healing being done to striking dummies or in instance. Overlays that show HP bars, mana bars, etc. do appear to update as expected.

I am unsure if the error below is related, but it is the only error in the debug log. It appears when first starting up IINACT. If the game is started first, it only appears once. If IINACT is started before the game, it appears twice in a row.

```
DEBUG-MACHINA: TCPNetworkMonitor Error in ProcessDataLoop inner code: Machina.Sockets.PcapException: Unable to get WinPcap device list.
 ---> System.DllNotFoundException: Dll was not found.
   at Machina.Sockets.PcapInterop.pcap_findalldevs_ex(String source, pcap_rmtauth& auth, IntPtr& alldevsp, StringBuilder errbuff)
   at Machina.Sockets.PcapDevice.GetAllDevices(String source, pcap_rmtauth& auth)
   --- End of inner exception stack trace ---
   at Machina.Sockets.PcapDevice.GetAllDevices(String source, pcap_rmtauth& auth)
   at Machina.Sockets.PCapCaptureSocket.GetDevice(UInt32 localAddress)
   at Machina.Sockets.PCapCaptureSocket.StartCapture(UInt32 localAddress, UInt32 remoteAddress)
   at Machina.ConnectionManager.Refresh()
   at Machina.TCPNetworkMonitor.ProcessDataLoop(CancellationToken token)```

**Comment by marzent** [comment]
You need the npcap driver for network parsing (assuming you are on windows here)

**Comment by SMNIRL** [comment]
I do have npcap installed, does it need to be in winpcap compatibility mode?

**Comment by marzent** [comment]
Yeah

**Comment by SMNIRL** [comment]
Reinstalling npcap in winpcap compatibility mode solved the issue, thanks.

**Comment by zeparu** [comment]
im having the same issue on Linux, i followed a guide for IINACT on the discord using setcap for network permissions
