### ISSUE TITLE
WebSocketServer lingers on update

### ISSUE THREAD

**Issue by yfthbr** [marzent/IINACT#115]
When the plugin is updated, the previous websocket server continues running on the configured port. The new version on init prints error as the port is already occupied:

```
15:14:36.544 | ERR | [IINACT] [OverlayPlugin] WS: Failed to start: System.Net.Sockets.SocketException (10013): Access denied.
	   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
	   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
	   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
	   at NetCoreServer.TcpServer.Start()
	   at RainbowMage.OverlayPlugin.WebSocket.ServerController.Start() in /home/runner/work/IINACT/IINACT/OverlayPlugin.Core/WebSocket/ServerController.cs:line 75
```

**Comment by marzent** [comment]
This should not be possible, as the WebSocketServer gets properly disposed of during unload... Most likely something crashed somewhere for that to happen (a larger log excerpt also showing the unload would be interesting here).

**Comment by 4i7** [comment]
## Investigation notes: possible lifecycle race around OverlayPlugin / WebSocket startup

I took a deeper look at this issue because the current behavior is a little more subtle than simply "`ServerController.Stop()` is missing".

I have **not reproduced the original `10013` yet**, so I don't want to claim that the following is conclusively what happened in the original report. However, there appear to be a couple of real lifecycle hazards in the current code that could allow an old plugin instance to keep creating/owning resources after an unload has started.

I looked at the current `main` implementation, particularly:

* `IINACT/Plugin.cs`
* `OverlayPlugin.Core/PluginMain.cs`
* `OverlayPlugin.Core/WebSocket/ServerController.cs`
* NetCoreServer's `TcpServer.Start()` / `Stop()` behavior
* Dalamud's plugin update/unload sequencing

### 1. `InitOverlayPlugin()` starts an untracked background initialization task

The first suspicious part is in `IINACT/Plugin.cs`.

`InitOverlayPlugin()` creates the `PluginMain`, but the actual initialization is started using a detached `Task.Run`:

```csharp
private RainbowMage.OverlayPlugin.PluginMain InitOverlayPlugin()
{
    var container = new RainbowMage.OverlayPlugin.TinyIoCContainer();

    // ...

    var overlayPlugin = new RainbowMage.OverlayPlugin.PluginMain(
        PluginInterface.AssemblyLocation.Directory!.FullName, logger, container);

    // ...

    Task.Run(() =>
    {
        overlayPlugin.InitPlugin(PluginInterface.ConfigDirectory.FullName);

        var registry = container.Resolve<RainbowMage.OverlayPlugin.Registry>();
        MainWindow.OverlayPresets = registry.OverlayTemplates;
        WebSocketServer =
            container.Resolve<RainbowMage.OverlayPlugin.WebSocket.ServerController>();
        MainWindow.Server = WebSocketServer;
        IpcProviders.Server = WebSocketServer;
        IpcProviders.OverlayIpcHandler =
            container.Resolve<
                RainbowMage.OverlayPlugin.Handlers.Ipc.IpcHandlerController>();

        // ...
    });

    return overlayPlugin;
}
```

The important part is not specifically `Task.Run` itself, but that the returned task is:

* not retained,
* not awaited,
* not cancelled,
* and not joined during `Plugin.Dispose()`.

So currently there is no lifecycle relationship between:

```text
Dalamud Plugin lifetime
```

and:

```text
OverlayPlugin initialization task lifetime
```

In other words, `Plugin.Dispose()` can complete without proving that this initialization task has completed.

---

### 2. `Dispose()` calls `DeInitPlugin()`, but does not synchronize with `InitPlugin()`

The corresponding unload path in `Plugin.cs` is roughly:

```csharp
public void Dispose()
{
    ClientState.EnterPvP -= EnterPvP;
    ClientState.LeavePvP -= LeavePvP;

    IpcProviders.Dispose();
    ZoneDownHookManager.Dispose();

    FfxivActPluginWrapper.Dispose();

    OverlayPlugin.DeInitPlugin();

    // ...
}
```

There is no synchronization with the `Task.Run(...)` above.

This means `InitPlugin()` and `DeInitPlugin()` are allowed to execute concurrently.

That looks especially relevant because WebSocket startup happens fairly late inside `PluginMain.InitPlugin()`.

---

### 3. The WebSocket server is registered early, but started much later

In `OverlayPlugin.Core/PluginMain.cs`, the `ServerController` is registered during phase 1:

```csharp
Status = @"Init Phase 1: WSServer";
_container.Register(new ServerController(_container));
```

but it is not started until much later in phase 2:

```csharp
// WSServer has to start after the LoadAddons() call because clients can
// connect immediately after it's initialized and that requires the
// event sources to be initialized.
if (Config.WSServerRunning)
{
    Status = @"Init Phase 2: WSServer";
    _container.Resolve<ServerController>().Start();
}
```

Meanwhile `DeInitPlugin()` does:

```csharp
try
{
    _container.Resolve<ServerController>().Stop();
}
catch (Exception ex)
{
    _logger.Log(
        LogLevel.Error,
        $"DeInitPlugin: Failed to stop WebSocket server {ex.Message}");
}
```

Taken separately, both paths look reasonable.

The problem is that there is nothing ordering them relative to each other.

A possible sequence is therefore:

```text
old plugin:

InitPlugin()
  |
  +-- phase 1
  |
  +-- ServerController registered
  |
  +-- phase 2 still running
          |
          |       plugin update / unload
          |              |
          |              +-- Plugin.Dispose()
          |              |
          |              +-- DeInitPlugin()
          |              |
          |              +-- ServerController.Stop()
          |              |      (server has not started yet)
          |              |
          |              +-- Dispose() returns
          |
          +-- InitPlugin() continues
          |
          +-- ServerController.Start()
              ^ old instance starts a resource after disposal
```

So even though `DeInitPlugin()` **does call `Stop()`**, that alone does not guarantee that the old instance cannot subsequently call `Start()`.

The lifecycle invariant I would normally expect here is:

```text
Plugin.Dispose() returned
    =>
all initialization owned by that Plugin instance has terminated
    =>
no code belonging to that instance can subsequently start
a WebSocket server, event source, timer, IPC handler, etc.
```

I don't think the current implementation guarantees that invariant.

---

### 4. `ServerController.Start()` also has a separate ownership hazard

There is another potentially relevant issue in `ServerController`.

Current startup is effectively:

```csharp
public void Start()
{
    Failed = false;

    try
    {
        var address =
            Config.WSServerIP == "*"
                ? IPAddress.Any
                : IPAddress.Parse(Config.WSServerIP);

        Server = new OverlayServer(
            address,
            Config.WSServerPort,
            Container);

        Server.OptionReuseAddress = true;

        Server.Start();

        OnStateChanged?.Invoke(
            this,
            new StateChangedArgs(true, false));
    }
    catch (Exception e)
    {
        // ...
    }
}
```

while shutdown is:

```csharp
public void Stop()
{
    try
    {
        Server?.Stop();
    }
    catch (Exception e)
    {
        // ...
    }

    // ...
}
```

`Start()` unconditionally replaces the `Server` field.

So if `Start()` is ever invoked twice without a successful `Stop()` in between, this is possible:

```text
Server = A
A.Start()

Server = B
B.Start()
```

At that point the controller has lost its reference to `A`.

A later:

```csharp
Server?.Stop();
```

can only stop `B`.

That means `ServerController` itself currently does not enforce single ownership of the listener.

This may not be the path that caused #115, but it seems worth hardening independently because the failure mode would be exactly an orphaned server that normal shutdown can no longer reach.

There is also no synchronization between `Start()` and `Stop()`, so concurrent calls are not serialized.

---

### 5. There is an even narrower `Start()` / `Stop()` race in the underlying server

NetCoreServer's startup sequence roughly does:

```text
create socket
set socket options
Bind()
Listen()
IsStarted = true
```

whereas `Stop()` begins with behavior equivalent to:

```csharp
if (!IsStarted)
    return false;
```

So if `Start()` and `Stop()` are allowed to race, there is theoretically a window such as:

```text
Start()
  create socket
  ...
                       Stop()
                         IsStarted == false
                         return
  Bind()
  Listen()
  IsStarted = true
```

This is another reason I think the higher-level IINACT lifecycle should serialize initialization and teardown rather than relying on `Stop()` to make arbitrary concurrent startup safe.

---

### 6. Why I think the boundary is probably in IINACT rather than Dalamud

From what I can tell, Dalamud's update path waits for the old plugin unload operation before proceeding with the replacement.

However, Dalamud cannot deterministically await IINACT's specific detached initialization Task because IINACT does not expose or join it. Dalamud does, however, include a bounded heuristic delay intended to give forgotten plugin tasks time to finish.

It cannot know that IINACT has done this internally:

```csharp
Task.Run(() => overlayPlugin.InitPlugin(...));
```

if that task is detached and `Dispose()` returns while it is still running.

So the problematic ownership boundary looks more like:

```text
Dalamud
  |
  | calls Dispose / waits for unload
  v
IINACT Plugin.Dispose()
  |
  | currently does not wait for
  v
detached OverlayPlugin InitPlugin task
```

rather than Dalamud intentionally loading two plugin generations concurrently.

---

### 7. One caveat: I would not equate the original `10013` with proof of an old IINACT listener

The issue report shows:

```text
SocketException (10013): Access denied
    at Socket.Bind(...)
    at NetCoreServer.TcpServer.Start()
```

That proves the new server failed during `Bind()`, but by itself it does not identify the owner/reason for the bind failure.

`ServerController` also sets:

```csharp
Server.OptionReuseAddress = true;
```

and Windows `SO_REUSEADDR` / exclusive-address behavior makes the exact meaning of a second bind somewhat dependent on the other socket and system state.

So I think these should be treated separately:

**Confirmed from the code:**

* OverlayPlugin initialization is detached from the IINACT plugin lifetime.
* `InitPlugin()` can theoretically overlap `DeInitPlugin()`.
* a disposed plugin generation can theoretically continue initialization.
* `ServerController.Start()` can replace an existing server reference.
* `Start()` / `Stop()` are not serialized.

**Not confirmed yet:**

* that the old IINACT instance was definitely the socket owner in the original report;
* that this specific race was the exact cause of the reported `10013`.

A larger unload/update log, as mentioned above, would still be useful for proving the original occurrence.

---

### 8. A deterministic reproduction should be possible

Rather than trying to reproduce this by repeatedly updating the plugin and hoping to hit the race, I think it could be tested deterministically.

For example:

1. pause/delay `InitPlugin()` immediately before:

   ```csharp
   _container.Resolve<ServerController>().Start();
   ```

2. unload the plugin while initialization is paused;

3. allow `Plugin.Dispose()` / `DeInitPlugin()` to finish;

4. release the initialization task;

5. check whether the old plugin generation reaches `ServerController.Start()` afterward.

If it does, that would demonstrate the lifecycle defect independently of the original `10013`.

Adding a temporary generation ID to logs such as:

```text
Plugin ctor
InitPlugin begin
Server.Start begin/end
Server.Stop begin/end
Plugin.Dispose begin/end
```

would also make old/new plugin instances easy to distinguish during an actual update.

---

### Possible fix direction

If this interpretation is correct, I think the fix may be relatively narrowly scoped, but I would want to validate the lifecycle interactions before assuming the implementation itself will be small.

I would avoid changing the broader OverlayPlugin architecture and instead make the host/lifecycle boundary explicit.

Something along these lines conceptually:

```text
IINACT owns OverlayPlugin initialization
        |
        +-- retain initialization task
        +-- prevent initialization after disposal begins
        +-- ensure Dispose establishes a terminal state
        +-- don't allow post-Dispose resource startup
```

and separately make `ServerController.Start()` idempotent / ownership-safe so that it cannot silently orphan an existing `OverlayServer`.

I would want to check carefully before simply blocking on the task in `Dispose()`, since an unconditional `.Wait()` / `.Result` could introduce a deadlock depending on what initialization touches.

If this analysis seems useful, I can try putting together a narrowly scoped PR with a deterministic lifecycle check and the smallest change needed to enforce the invariant, rather than doing a broader refactor.
