### ISSUE TITLE
Exception - Collection was modified after the enumerator was instantiated

### ISSUE THREAD

**Issue by oorzkws** [marzent/IINACT#52]
Came up just running through LOTA, had the log open looking for other plugin issues. Just figured I'd mention it. Searched PRs and issues, don't see it otherwise mentioned, happened on v2.1.4.0
```
08:18:46.430 | ERR [Advanced Combat Tracker] Encounter - [00:14] 8:18:31 AM -> maxhealward-*()
System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.Collections.Generic.SortedList`2.Enumerator.MoveNext()
   at Advanced_Combat_Tracker.EncounterData.GetAllies(Boolean allowLimited) in /home/runner/work/IINACT/IINACT/NotACT/Datatypes/EncounterData.cs:line 455
   at Advanced_Combat_Tracker.EncounterData.GetMaxHeal(Boolean ShowType, Boolean CountWards, Boolean UseSuffix) in /home/runner/work/IINACT/IINACT/NotACT/Datatypes/EncounterData.cs:line 588
   at Advanced_Combat_Tracker.Resources.NotActMainFormatter.EncounterFormatSwitch(EncounterData data, List`1 selectiveAllies, String varName, String extra) in /home/runner/work/IINACT/IINACT/NotACT/Resources/NotActMainFormatter.cs:line 2166
   ```

**Comment by marzent** [comment]
Thanks for reporting!

This is fixed with 2.1.5.0
