### ISSUE TITLE
Crash on area switch

### ISSUE THREAD

**Issue by Kurochi51** [marzent/IINACT#56]
I was doing the new raid quests, and after talking to an npc which led to an area switch, the game just crashed to desktop. Only log I could find regarding it.
```

Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Buffer.__Memmove(Byte*, Byte*, UIntPtr)
--------------------------------
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Runtime.InteropServices.Marshal.CopyToManaged[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, Byte[], Int32, Int32)
   at FFXIV_ACT_Plugin.Memory.MemoryReader.ReadCombatant.Read(IntPtr)
   at FFXIV_ACT_Plugin.Memory.MemoryProcessors.CombatantProcessor.RefreshCombatantInternal(FFXIV_ACT_Plugin.Common.Models.Combatant, IntPtr, Boolean)
   at FFXIV_ACT_Plugin.Memory.MemoryProcessors.CombatantProcessor.RefreshCombatant(FFXIV_ACT_Plugin.Common.Models.Combatant, IntPtr, Boolean)
   at FFXIV_ACT_Plugin.Memory.CombatantManager.Refresh()
   at FFXIV_ACT_Plugin.Memory.BenchmarkRepository.Measure(System.String, System.Action)
   at FFXIV_ACT_Plugin.Memory.ScanMemory.Run(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

**Comment by marzent** [comment]
Well you could say `Internal CLR error. (0x80131506)` is Microsofts fault and open an issue for the runtime...

However `ReadCombatant` was the one I was afraid of since it is not really thread-safe and should happen on a framework tick really (as should actually all of these, but it seemed "good enough" for me during testing, so didn't think it was that big of an issue)

Hopefully 2.0.2.2 fixes this (the above for sure, but will leave this open just in case there are similar issues).

Plus if MS were to fix it (with something almost impossible for them to reproduce), it would probably be a `AccessViolationException` which wouldn't be much more helpful here...

**Comment by computerquip** [comment]
I had a similar crash. Once when updating the plugin in-game, another during a scene switch during The Porta Decuma trial.

My dalamud.log is posted in its entirety here: https://gist.github.com/computerquip/15220e642a542a2d3c2bf9d985aa88e4

There's some weirdness here: https://gist.github.com/computerquip/15220e642a542a2d3c2bf9d985aa88e4#file-gistfile1-txt-L214
but I can't discern what constitutes a crash here.

**Comment by Kurochi51** [comment]
If it was a CTD, you'll probably have more luck finding an actual crash log in `dalamud.boot.log`

**Comment by computerquip** [comment]
Here's the [dalamud.boot.log](https://gist.githubusercontent.com/computerquip/9d1719ed36e09b48602aedfb27dbde29/raw/9fbb14adf806491b9fb3da03918f8f8dfd1c216e/dalamud.boot.log). It does seem to have a similar error. 

```
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Buffer.__Memmove(Byte*, Byte*, UIntPtr)
--------------------------------
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.Runtime.InteropServices.Marshal.CopyToManaged[[System.Byte, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](IntPtr, Byte[], Int32, Int32)
   at FFXIV_ACT_Plugin.Memory.MemoryReader.ReadCombatant.Read(IntPtr)
   at FFXIV_ACT_Plugin.Memory.MemoryProcessors.CombatantProcessor.RefreshCombatantInternal(FFXIV_ACT_Plugin.Common.Models.Combatant, IntPtr, Boolean)
   at FFXIV_ACT_Plugin.Memory.MemoryProcessors.CombatantProcessor.RefreshAndAddCombatant(FFXIV_ACT_Plugin.Common.Models.Combatant, IntPtr, FFXIV_ACT_Plugin.Common.Models.Combatant[])
   at FFXIV_ACT_Plugin.Memory.CombatantManager.Rescan()
   at FFXIV_ACT_Plugin.Memory.BenchmarkRepository.Measure(System.String, System.Action)
   at FFXIV_ACT_Plugin.Memory.ScanMemory.Run(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
```

**Comment by marzent** [comment]
Should be resolved with handling Combatant data reads on Framework ticks and haven't heard any more reports of this happening, so closing it for now

**Comment by arghblargh** [comment]
Got 2 CTDs today with this in dalamud.boot.log:
`Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Buffer.__Memmove(Byte*, Byte*, UIntPtr)
--------------------------------
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at IINACT.FfxivActPluginWrapper.MobDataRefresh(Dalamud.Plugin.Services.IFramework)
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(System.Action)
   at Dalamud.Utility.EventHandlerExtensions.InvokeSafely(OnUpdateDelegate, Dalamud.Game.Framework)
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr)`

Also in the Porta Decumana trial and another upon loading into a duty.

**Comment by marzent** [comment]
This really shouldn't happen anymore, but I can put some additional safety there as well...

**Comment by marzent** [comment]
Feel free to create a new issue if this ever happens again with 2.4+ @arghblargh
