### ISSUE TITLE
Failed to initialize SAPI TTS engine

### ISSUE THREAD

**Issue by kutsan** [marzent/IINACT#65]
I'm getting the following error on my Mac (with XIV on MAC) and it is causing FFXIV to crash. I'm not sure what the problem is but I can provide debugging information if it's needed.

```
2023-08-29 22:37:45.146 +01:00 [WRN] [IINACT] Failed to initialize SAPI TTS engine
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Speech.Internal.ObjectTokens.ObjectTokenCategory.Create(String sCategoryId)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToDefaultAudioDevice()
   at IINACT.TextToSpeechProvider..ctor() in /home/runner/work/IINACT/IINACT/IINACT/TextToSpeechProvider.cs:line 20
```

https://github.com/marzent/IINACT/blob/539e0d3983fc9531f9dd27879f952711f41b66b4/IINACT/TextToSpeechProvider.cs#L20

**Comment by marzent** [comment]
This is not an error, but just a warning (and completely expected when trying to use `System.Speech` under Wine).

Your game is crashing for a different reason.
