### ISSUE TITLE
v2.6.2.2 - This plugin failed to load.

### ISSUE THREAD

**Issue by abitlegacy** [marzent/IINACT#94]
Updated to v2.6.2.2 late tonight after running the previous versions without issues. Now the plugin fails to load with this log entry:

```
2024-07-16 22:34:56.281 -07:00 [ERR] [LOCALPLUGIN] Exception in plugin constructor
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Machina.FFXIV, Version=2.3.9.8, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Machina.FFXIV, Version=2.3.9.8, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Machina.FFXIV, Version=2.3.9.8, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Machina.FFXIV, Version=2.3.9.8, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.Load(AssemblyName assemblyName) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\ManagedLoadContext.cs:line 207
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 130
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 431
```

**Comment by Helios747** [comment]
I'm reading that Windows Defender is unhappy about one of the DLLs IINACT ships with. Try excluding `%AppData%/XIVLauncher` in Windows Defender, uninstall the plugin in `/xlplugins` and reinstall.

**Comment by abitlegacy** [comment]
Confirmed that Windows Defender picked up the Machine.FFXIV.dll - after excluding %appdata%\XIVLauncher, deleting the plugin, relaunching, and then re-installing the plugin everything appears to be fully functional again. Thanks for the advice!

**Comment by marzent** [comment]
Can you recheck with the problem still happens with Defender without whitelisting on 2.6.2.3?

**Comment by abitlegacy** [comment]
I removed the whitelist and updated. It still loads and functions correctly without the whitelist.
