### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by dzfawks221** [marzent/IINACT#95]
#94 
This may be tied to the previous issue or maybe I'm failing to do something obvious after microsoft defender was tagging it as malicious I whitelisted the folder, removed IINACT and re-installed IINACT but it failed to install.

```
08:40:29.245 | ERR | [LOCALPLUGIN] Exception in plugin constructor
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
	 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
	 ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
	   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
	   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
	   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
	   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
	   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
	   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at FetchDependencies.FetchDependencies.DownloadFile(String url, String path) in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 83
	   at FetchDependencies.FetchDependencies.GetFfxivPlugin() in /home/runner/work/IINACT/IINACT/FetchDependencies/FetchDependencies.cs:line 38
	   at IINACT.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager, IGameNetwork gameNetwork, IClientState clientState, IDataManager dataManager, IChatGui chatGui, IPluginLog pluginLog) in /home/runner/work/IINACT/IINACT/IINACT/Plugin.cs:line 70
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 130
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 431
08:40:29.260 | ERR | [LOCALPLUGIN] Error while loading "IINACT", failed to bind and call the plugin constructor

```

**Comment by Linoa235** [comment]
Same for me yesterday I had no problem I connect to the game I got the error message 504 cactbot alert

**Comment by marzent** [comment]
Yeah there are a few network issues going on with the backend atm, should hopefully be fixed soon.

**Comment by marzent** [comment]
Should be fixed now, feel free to open a new issues for any other errors!
